//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Putilin2018.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class MyDatabaseEntities : DbContext
    {
        public MyDatabaseEntities()
            : base("name=MyDatabaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Voditel> Voditel { get; set; }
        public virtual DbSet<Группы_задач> Группы_задач { get; set; }
        public virtual DbSet<Получатель> Получатель { get; set; }
        public virtual DbSet<Пункт_доставки> Пункт_доставки { get; set; }
        public virtual DbSet<Тип_ТС> Тип_ТС { get; set; }
        public virtual DbSet<Задача> Задача { get; set; }
        public virtual DbSet<Автомобиль> Автомобиль { get; set; }
        public virtual DbSet<Маршрут> Маршрут { get; set; }
        public virtual DbSet<Пункты_регулярного_маршрута> Пункты_регулярного_маршрута { get; set; }
        public virtual DbSet<Рейс> Рейс { get; set; }
        public virtual DbSet<Ремонт> Ремонт { get; set; }
        public virtual DbSet<Статус_заявки> Статус_заявки { get; set; }
        public virtual DbSet<Пункты_рейса> Пункты_рейса { get; set; }
    
        public virtual int update_arrival_time(Nullable<int> point_of_race_ID, Nullable<int> confirmation_code, Nullable<System.TimeSpan> confirmation_time)
        {
            var point_of_race_IDParameter = point_of_race_ID.HasValue ?
                new ObjectParameter("point_of_race_ID", point_of_race_ID) :
                new ObjectParameter("point_of_race_ID", typeof(int));
    
            var confirmation_codeParameter = confirmation_code.HasValue ?
                new ObjectParameter("confirmation_code", confirmation_code) :
                new ObjectParameter("confirmation_code", typeof(int));
    
            var confirmation_timeParameter = confirmation_time.HasValue ?
                new ObjectParameter("confirmation_time", confirmation_time) :
                new ObjectParameter("confirmation_time", typeof(System.TimeSpan));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("update_arrival_time", point_of_race_IDParameter, confirmation_codeParameter, confirmation_timeParameter);
        }
    }
}
