//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Putilin2018.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class MyDatabaseEntities : DbContext
    {
        public MyDatabaseEntities()
            : base("name=MyDatabaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Voditel> Voditel { get; set; }
        public virtual DbSet<Группы_задач> Группы_задач { get; set; }
        public virtual DbSet<Получатель> Получатель { get; set; }
        public virtual DbSet<Пункт_доставки> Пункт_доставки { get; set; }
        public virtual DbSet<Тип_ТС> Тип_ТС { get; set; }
        public virtual DbSet<Задача> Задача { get; set; }
        public virtual DbSet<Автомобиль> Автомобиль { get; set; }
        public virtual DbSet<Маршрут> Маршрут { get; set; }
        public virtual DbSet<Пункты_регулярного_маршрута> Пункты_регулярного_маршрута { get; set; }
        public virtual DbSet<Рейс> Рейс { get; set; }
        public virtual DbSet<Ремонт> Ремонт { get; set; }
        public virtual DbSet<Статус_заявки> Статус_заявки { get; set; }
        public virtual DbSet<Пункты_рейса> Пункты_рейса { get; set; }
        public virtual DbSet<ViewРасходГСМ> ViewРасходГСМ { get; set; }
    
        public virtual int update_arrival_time(Nullable<int> point_of_race_ID, Nullable<int> confirmation_code)
        {
            var point_of_race_IDParameter = point_of_race_ID.HasValue ?
                new ObjectParameter("point_of_race_ID", point_of_race_ID) :
                new ObjectParameter("point_of_race_ID", typeof(int));
    
            var confirmation_codeParameter = confirmation_code.HasValue ?
                new ObjectParameter("confirmation_code", confirmation_code) :
                new ObjectParameter("confirmation_code", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("update_arrival_time", point_of_race_IDParameter, confirmation_codeParameter);
        }
    
        [DbFunction("MyDatabaseEntities", "get_last_racenumber")]
        public virtual IQueryable<Nullable<int>> get_last_racenumber()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<Nullable<int>>("[MyDatabaseEntities].[get_last_racenumber]()");
        }
    
        [DbFunction("MyDatabaseEntities", "get_cost_report")]
        public virtual IQueryable<get_cost_report_Result> get_cost_report(Nullable<System.DateTime> date_start, Nullable<System.DateTime> date_end)
        {
            var date_startParameter = date_start.HasValue ?
                new ObjectParameter("date_start", date_start) :
                new ObjectParameter("date_start", typeof(System.DateTime));
    
            var date_endParameter = date_end.HasValue ?
                new ObjectParameter("date_end", date_end) :
                new ObjectParameter("date_end", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<get_cost_report_Result>("[MyDatabaseEntities].[get_cost_report](@date_start, @date_end)", date_startParameter, date_endParameter);
        }
    
        [DbFunction("MyDatabaseEntities", "get_last_fuel_and_distance")]
        public virtual IQueryable<get_last_fuel_and_distance_Result> get_last_fuel_and_distance()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<get_last_fuel_and_distance_Result>("[MyDatabaseEntities].[get_last_fuel_and_distance]()");
        }
    }
}
