//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Putilin2018.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewРасходГСМ
    {
        public string Название_группы { get; set; }
        public string Название_задачи { get; set; }
        public System.DateTime Дата_рейса { get; set; }
        public int Расход_ГСМ { get; set; }
        public int Группа_задачID { get; set; }
        public int РейсID { get; set; }
        public int ЗадачаID { get; set; }
    }
}
