//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Putilin2018.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Получатель
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Получатель()
        {
            this.Пункты_рейса = new HashSet<Пункты_рейса>();
        }
    
        public int Id { get; set; }
        public string ФИО { get; set; }
        public string E_mail { get; set; }
        public string Телефон { get; set; }
        public int Пункт_доставкиID { get; set; }
    
        public virtual Пункт_доставки Пункт_доставки { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Пункты_рейса> Пункты_рейса { get; set; }
    }
}
