//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Putilin2018.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Получатель
    {
        public int Id { get; set; }
        public string ФИО { get; set; }

        [Display(Name = "E-mail")]
        public string E_mail { get; set; }
        public string Телефон { get; set; }
        public int Пункт_доставкиID { get; set; }
    
        public virtual Пункт_доставки Пункт_доставки { get; set; }
    }
}
