//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Putilin2018.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Пункты_регулярного_маршрута
    {
        public int Id { get; set; }
        public int МаршрутID { get; set; }
        public int Пункт_доставкиID { get; set; }
        public int ЗадачаID { get; set; }
        public Nullable<System.TimeSpan> Время_плановое { get; set; }
        public string Примечание { get; set; }
    
        public virtual Задача Задача { get; set; }
        public virtual Маршрут Маршрут { get; set; }
        public virtual Пункт_доставки Пункт_доставки { get; set; }
    }
}
