//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Putilin2018.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Пункт_доставки
    {
        public int Id { get; set; }
        
        [Display(Name = "Название пункта")]
        public string Название_пункта { get; set; }
        public string Адрес { get; set; }
        public string Регулярность { get; set; }
    }
}
