//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Putilin2018.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Пункты_рейса
    {
        public int Id { get; set; }
        public int РейсID { get; set; }
        public int Пункт_доставкиID { get; set; }
        public int ПолучательID { get; set; }
        public int ЗадачаID { get; set; }
        public System.TimeSpan Время_плановое { get; set; }
        public int УсловныйКод { get; set; }
        public System.TimeSpan Время_фактическое { get; set; }
        public string Примечание { get; set; }
    
        public virtual Задача Задача { get; set; }
        public virtual Получатель Получатель { get; set; }
        public virtual Пункт_доставки Пункт_доставки { get; set; }
        public virtual Рейс Рейс { get; set; }
    }
}
