//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Putilin2018.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Рейс
    {
        public int Id { get; set; }
        [Display(Name = "Номер путевого листа")]
        public string Номер_путевого_листа { get; set; }

        [DataType(DataType.Date) ]
        [DisplayFormat(DataFormatString = "{0:dd.MM.yyyy}")]
        //[DisplayFormat(DataFormatString = "{0:dd.MM.yyyy}", ApplyFormatInEditMode = true)]
        [Display(Name = "Дата рейса")]
        public System.DateTime Дата_рейса { get; set; }

        [Display(Name = "ГСМ на выезде")]
        public int Остаток_ГСМ_на_въезде { get; set; }

        [Display(Name = "ГСМ выдано")]
        public int Выдано_ГСМ { get; set; }
        public int Нач_спидометр { get; set; }
        public int Норма { get; set; }
        public int Пробег { get; set; }

        [Display(Name = "Расход ГСМ")]
        public int Расход_ГСМ { get; set; }

        [Display(Name = "Водитель")]
        public int ВодительID { get; set; }
        [Display(Name = "Задача")]
        public int ЗадачаID { get; set; }
        [Display(Name = "Автомобиль")]
        public int АвтомобильID { get; set; }
        public string Примечание { get; set; }

        [Display(Name = "Водитель")]
        public virtual Voditel Voditel { get; set; }
        [Display(Name = "Автомобиль")]
        public virtual Автомобиль Автомобиль { get; set; }
        [Display(Name = "Задача")]
        public virtual Задача Задача { get; set; }
    }
}
