//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Putilin2018
{
    using System;
    using System.Collections.Generic;
    
    public partial class Voditel
    {
        public int Id { get; set; }
        public string fio { get; set; }
        public Nullable<System.DateTime> license_expire { get; set; }
        public string categories { get; set; }
    }
}
